// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const StoreTypes = sequelize.define('storeTypes', {
    storetype: {
      type: DataTypes.ENUM('room_temperature','low_temperature','refrigerated_storage','fronze_storage'),
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'store_types',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  StoreTypes.associate = (models) => {
    StoreTypes.belongsTo(models.detailOrderInfos, {
      foreignKey: {
        name: 'detailOrderInfoSeqKey',
        field: 'DetailOrderInfoSeq',
      },
      targetKey: 'seq',
      as: 'detailOrderInfoSeq',
    });
  };

  return StoreTypes;
};
