// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const OrderInfos = sequelize.define('orderInfos', {
    seq: {
      type: DataTypes.BIGINT,
      primaryKey: true,
      allowNull: false,
    },
    customerCompany: {
      type: DataTypes.STRING,
      field: 'customer_company',
    },
    customerManagerName: {
      type: DataTypes.STRING,
      field: 'customer_manager_name',
    },
    customerPhone: {
      type: DataTypes.STRING,
      field: 'customer_phone',
    },
    customerEmail: {
      type: DataTypes.STRING,
      field: 'customer_email',
    },
    customerMemo: {
      type: DataTypes.STRING,
      field: 'customer_memo',
    },
    regDate: {
      type: DataTypes.DATE,
      field: 'reg_date',
      allowNull: false,
    },
     manager : {
      type: DataTypes.ENUM('1','2','3','4'),
      field: 'manager',
      allowNull: true,
    },
    estimateDoc : {
      type: DataTypes.STRING,
      field: 'estimateDoc',
      allowNull: true,
    },
    contractDoc : {
      type: DataTypes.STRING,
      field: 'contractDoc',
      allowNull: true,
    },
    contract_status: {
      type: DataTypes.ENUM,
      values:["no_response", "no_negotiation","compare_otherCompany","inquire_storeType","ongoing_negotiation","complete_negotiation"],
      allowNull: true,
    },
    history : {
      type: DataTypes.STRING,
      field: 'history',
      allowNull: true,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'orderInfos',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  OrderInfos.associate = (models) => {
  };

  return OrderInfos;
};
